### ISSUE TITLE
Feature request: adjust view sizes

### ISSUE THREAD

**Issue by gdevenyi** [BIC-MNI/Register#11]
sometimes I'm interested in a specific view, it would be nice if I could resize it to make it larger.

**Comment by rdvincent** [comment]
I'm assuming you mean dynamically dragging the dividers when register is running?

**Comment by gdevenyi** [comment]
Yes, exactly

**Comment by rdvincent** [comment]
OK. I'll look into it. You already can change them in the configuration, as you may know:

register -global Slice_top_view_height 0.5

will make the top (transverse) slice larger than the default. Slice_middle_view_height will change the relative height of the middle (sagittal) image.

**Comment by gdevenyi** [comment]
Cheers, will try that out thanks!

**Comment by rdvincent** [comment]
@gdevenyi if you want to try this, check out the rdv-n-up branch. It lets you load up to 8 volumes simultaneously. The horizontal dividers are also now draggable.

**Comment by gdevenyi** [comment]
So, it loads multiple scans nicely, however I can't figure out how to drag the dividers...

**Comment by rdvincent** [comment]
You have to just place your mouse cursor near the horizontal dividers, click, and drag. There's no visual indication yet.

**Comment by gdevenyi** [comment]
So far, no dice, can't seem to find anything draggable.

**Comment by rdvincent** [comment]
Hmm... Not sure why it wouldn't work for you. Again, it only lets you move the horizontal separators between the three slice views.

![image](https://cloud.githubusercontent.com/assets/1395526/15268316/9c359102-19a8-11e6-89b0-fcd8bd599dd4.png)

**Comment by gdevenyi** [comment]
Did a fresh install on my laptop tonight, adjustment works here.

I think perhaps my repeated `make install` might have some leftovers. I will purge and reinstall tomorrow to see if it works.

**Comment by gdevenyi** [comment]
Worksforme after a purge of my install dir and `make install`.

**Comment by gdevenyi** [comment]
Fixed
