### ISSUE TITLE
Register screenshots bug

### ISSUE THREAD

**Issue by gdevenyi** [BIC-MNI/Register#12]
1) I didn't know there was a screenshot feature in register, accidental keystroked "s" and got a screenshot.

Attached, as you can see isn't correct
![register_image_1](https://cloud.githubusercontent.com/assets/3001850/15250178/7a45d42e-18f1-11e6-9ac0-e7599074e689.jpg)

**Comment by rdvincent** [comment]
The existing code uses ImageMagick "import". My guess is that for some monitor setups this doesn't work correctly. I may re-implement this using a different approach.

**Comment by rdvincent** [comment]
@gdevenyi Also, what is the date of your register binary?

**Comment by gdevenyi** [comment]
git built from register devel this morning.

**Comment by rdvincent** [comment]
Is there anything unusual about your setup (dual monitor, e.g.)?

**Comment by gdevenyi** [comment]
Single 1080p 27" widescreen, Ubuntu 14.04 unity.

**Comment by rdvincent** [comment]
@gdevenyi Check it again when you have a moment...

**Comment by gdevenyi** [comment]
Now saves a screenshot of the last clicked window as a pnm file. (properly)

**Comment by rdvincent** [comment]
Yes, we don't include a tiff library in our default build, so I used our built-in ppm support.

**Comment by gdevenyi** [comment]
No problem. I don't use this anyways, but accidentally came across this bug and thought I'd report it.

**Comment by gdevenyi** [comment]
Resolved
