### ISSUE TITLE
rdv branch "blending" not working

### ISSUE THREAD

**Issue by gdevenyi** [BIC-MNI/Register#13]
Blend slider seems to be no longer properly scaling the intensities between each scan.

Test case:
load same scan twice, move blend slider, intensity changes when it shouldn't since the scan is the same.

**Comment by rdvincent** [comment]
Yes, the only combination mode that works as intended right now is "Weights", and it only works for the first two volumes. Getting this working in some reasonable way is one of the stumbling blocks I'm trying to overcome with this branch.

**Comment by rdvincent** [comment]
@gdevenyi Check out the latest. All volumes have their own blend slider, and separate controls for "Blended", "Opaque", or "Off".

**Comment by gdevenyi** [comment]
Well, that certainly works now, but that completely breaks my standard "how are these different?" method of sliding left-right to see how the image changes. I presume this is still a work in progress?

**Comment by rdvincent** [comment]
You can swap the volume 0 and 1 images quickly using the 'r' and 'e' keys.

**Comment by rdvincent** [comment]
Shift 'R' and 'E' will swap them immediately, without shift they move slowly.

**Comment by rdvincent** [comment]
@gdevenyi To address your earlier question, yes, this is a work in progress - that's why it is still distinct from the "develop" branch, although I expect to ultimately merge this with develop.

Let me know if the 'R'/'E' key trick is insufficient. What I might do is re-add a slider under the "merged" panel, with similar behavior to the original blend slider. It might do something like trade off the weights for two different subgroups of images.

**Comment by gdevenyi** [comment]
r/e and R/E work okay, I do like the slider because I can control the speed a bit better. Perhaps it would be better if r/e jumped in a bit larger steps.

**Comment by rdvincent** [comment]
@gdevenyi I'll do what I describe above - I'll add a slider under the "merged" panel on the right that works similarly to the original, just extended somehow to the N-volume case.

**Comment by gdevenyi** [comment]
Great, I see how the "n-volume" case is definitely tough for blending purposes. Personally, I'm okay with the "quick blend" stuff only making sense for 2-volume.

The n-volume display overlap is great for checking alignments alone, even if we can never sort a sensible quick blend.

**Comment by rdvincent** [comment]
@gdevenyi One question, though, is what is the best arrangement of initial colour mappings for the loaded volumes. I also wonder if custom colour maps would be useful.

**Comment by gdevenyi** [comment]
I think it's reasonable to just rotate through the standard maps as n increases.

As for custom colour maps, I requested those in #6 :)

**Comment by gdevenyi** [comment]
Resolved
