### ISSUE TITLE
Control of colour map for input images?

### ISSUE THREAD

**Issue by gdevenyi** [BIC-MNI/Register#14]
Display has the ability to specify the default colour map on the command line, register doesn't seem to have that option.

Is there a way to set the default maps for the inputs?

**Comment by rdvincent** [comment]
I did add "-grey", "-spectral", etc. options recently. There is also the ability to specify a ".ccd" file on the command line (as used for voxel values in Display). A custom .ccd file will select that colour map for the following volume(s).

**Comment by gdevenyi** [comment]
That works! Great.

**Comment by gdevenyi** [comment]
Help needs updating of course then :)

**Comment by rdvincent** [comment]
@gdevenyi Please see the develop branch - I updated the man page accordingly.

**Comment by gdevenyi** [comment]
Wonderful thanks!
