### ISSUE TITLE
Extra precision for outputs

### ISSUE THREAD

**Issue by andrewjanke** [BIC-MNI/Register#2]
From Claude: 

---

Hi Andrew,

User_interface/Include/global_variables.h

```
DEF_GLOBAL( Position_values_format, STRING, "%.2lf" )
```

I suggest to add an extra decimal value to the x, y, z positions.
It was %.1lf before.

This is becoming more and more useful and not only for bigbrain.

What do you think?

**Comment by rdvincent** [comment]
Addressed by 2d150e5d806028d8f0a66d5f80ab052c2d487c78
