### ISSUE TITLE
Extra command line option

### ISSUE THREAD

**Issue by yassinebha** [BIC-MNI/Register#3]
Hi,
We use register in our lab (https://github.com/simexp) very often  especially for quality check (QC) of preprocessed data. We are in a process of validating a QC procedure based on register but we need to have access to more command line options like:
1. Slices selection
2. Synced views
3. Color scale threshold

Do you think register allow these kind tweaks? or in futures release?
Thanks

**Comment by rdvincent** [comment]
You can set the initial state of the "Synced/Not Synced" button by specifying the following:

```
register -global Initial_volumes_synced True <file1> <file2> ...
```

Alternatively, you can also set the initial value of variables such as this from the register_UI.globals file.

I don't believe your other two suggestions are currently possible, but I will try to add them. It should not be difficult. Can you clarify exactly what you need? You want to specify what slice is initially displayed in the view? And which aspects of the colour scale do you need to set?

**Comment by lunebellec** [comment]
Hi Robert,

re slice selection, we have set up a [quality control protocol](https://github.com/SIMEXP/niak_manual/blob/master/qc_manual_v1.0/qc_manual_niak.pdf) to assess some registration process, which requires to examine a series of given slices. We use register for visualization, but we are scripting the process, and try to automate all steps as much as possible. Being able to set the initial view coordinates through command line would be a big step forward, but not a complete solution. I am wondering if this could not be solved with tags. If we loaded a series of tags, would it be possible to switch the view such that it's centered on the next tag point? is it possible to load a tag file from the command line?  

Re setting min/max of the image, by default register uses the actual min/max of the volume. This has two limitations: sometimes a volume has a natural scale, e.g. a correlation between -1 and 1, and one wants to systematically use the same min/max in a series of visualization. The second limitation is that you generally have outlier values in an MRI volume, such that using the min/max of the image to set the min/max of the color scale result in very poor contrast in the brain. You then have to change the min/max manually to get a nice contrast in the brain. Doing this hundreds of times during QC is not fun. There would be ways to automatically set the colorbar, e.g. using the 5th and 95th percentiles of the image, which may work better. We are planning on implementing such a method outside of register and then use an option to set the min/max in register from the command line.

I hope this clarifies what features we need. Best,

Pierre

**Comment by rdvincent** [comment]
Thanks, Pierre. You can definitely load a .tag file in the command line. We could certainly add a command line option or global that told Register to start the cursor at a numbered tag point. Alternatively, we could specify an initial position in world or voxel coordinates.

Currently Display does histogramming to set the contrast. But rather than trying to duplicate that functionality, I can more easily add a global to tell Register the preferred absolute minimum and maximum color values for each panel.

**Comment by lunebellec** [comment]
The proposed solution for min/max would be great. 

The proposed solution for tags would fix our problem to some degree, we would only have to re-open register for each tag. 

I don't know how much work this would be, but having two small buttons under "save tags" with

< tag >

(< and > would be the buttons) to centre the view on the tag points would be useful both for tag users and our purpose. Simply having some key bindings would also work. 

We'd very much appreciate if you were able to implement any of these solutions.

**Comment by rdvincent** [comment]
If you load a tag file, you can step through each of the tags very easily. There are "next tag" and "previous tag" buttons in the lower right portion of the UI. The buttons look like "^" and "v". Alternatively, the up arrow and down arrow keys are already bound to these functions.

**Comment by lunebellec** [comment]
Perfect!! I somehow missed that for a decade. So this solves our problem regarding slice positions, we'll simply load a tag file and let user flip through them to check all views. So the only open issue is to set the min/max of the color maps. Thanks so much for your rapid responses.

**Comment by rdvincent** [comment]
You're welcome.

**Comment by yassinebha** [comment]
Thanks a lot  Robert it is awesome, do you think at this stage I can easily bind left and right keys to slide the blend cursor?
Best

**Comment by rdvincent** [comment]
@yassinebha Changing the key bindings requires modifying the code (unlike Display, which can read key bindings from a file). The main key bindings are implemented in User_interface/event_callbacks/slice_events.c. Left and right arrow keys are currently bound to the changing the slice coordinate by +1 or -1, so I would rather not change that binding. Is there some other key pair we could use?

**Comment by yassinebha** [comment]
r : for right
e: for left
would be excellent. Thanks a lot

**Comment by rdvincent** [comment]
@yassinebha OK, the code is checked into the develop branch: cc8fd3bc78c40e42b3b9f5f42051df6dc44f7d51

**Comment by yassinebha** [comment]
Thanks Robert, I wasn't able to make theses options works from the development version, [Here](https://github.com/yassinebha/Docker/blob/master/minctools/Dockerfile) is the instructions I used to build docker machine with the development version of minc-tools. The install completed but I don't know how to source the minc tools.
Thanks again

**Comment by rdvincent** [comment]
Hi Yassine,

I've modified the Dockerfile - this version seems to work.

```
-bert
```

On Mon, Oct 19, 2015 at 1:52 PM, Yassine Benhajali <notifications@github.com

**Comment by yassinebha** [comment]
Sorry, I don't see any pull request or merge on my github repos, I'm i wrong?

**Comment by rdvincent** [comment]
@yassinebha Sorry, I tried to add it as en enclosure but evidently that does not work. Here it is as a dropbox link: https://www.dropbox.com/s/xbm69grncj45drm/Dockerfile?dl=0
